### ISSUE TITLE
installation on freebsd

### ISSUE THREAD

**Issue by moracca** [topfunky/gruff#106]
I am not able to install with gem install gruff because it complains about not being able to install rmagick, because magick-config is not present.  Elsewhere I've seen to install the libmagick-dev package, with plenty of instructions for ubuntu and osx but I cannot figure out how to do this on freebsd.

slice-lab# gem install gruff
Building native extensions.  This could take a while...
ERROR:  Error installing gruff:
        ERROR: Failed to build gem native extension.

```
    /usr/local/bin/ruby19 extconf.rb
```

checking for Ruby version >= 1.8.5... yes
checking for cc... yes
checking for Magick-config... no
Can't install RMagick 2.13.2. Can't find Magick-config in /sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin

slice-lab# pkg_add -r libmagick-dev
Error: Unable to get ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-stable/Latest/libmagick-dev.tbz: File unavailable (e.g., file not found, no access)

**Comment by Watson1978** [comment]
Could you please use latest gruff & RMagick ? Then, you can solve this issue, I think.
