### ISSUE TITLE
Draw vertical lines on line graph

### ISSUE THREAD

**Issue by davebcn87** [topfunky/gruff#119]
Hello,

I'm trying to print a vertical line for each label in a line graph. Is this possible?

**Comment by Watson1978** [comment]
Please set `true` via [Gruff::Line#show_vertical_markers=](https://www.rubydoc.info/gems/gruff/0.13.0/Gruff/Line#show_vertical_markers=-instance_method)

Example)
<img src="https://raw.githubusercontent.com/topfunky/gruff/master/test/expected/line_show_vertical_markers.png">
