### ISSUE TITLE
Option to make bar charts grouped with spacing

### ISSUE THREAD

**Issue by runephilosof** [topfunky/gruff#131]
It would be nice with a spacing option so that you could generate a bar chart where each group is spaced more apart than the bars in the group.

In the README you have a bar chart example with Jimmy, Charles and Julie for four dates.
I would like to have a bitter space between the dates than between Jimmy, Charles and Julie inside each date.

Did I explain it properly enough?

**Comment by BlakeCampbells** [comment]
I would like this feature as well, I saw issue #7 has the same request. Any updates on this?

**Comment by donv** [comment]
If you have the time, please make a pull request, and I will merge it.

**Comment by Watson1978** [comment]
this issue should be resolved with  #400
