### ISSUE TITLE
Cryptic error when graph labels are not strings

### ISSUE THREAD

**Issue by jbcden** [topfunky/gruff#137]
I ran into the error `no implicit conversion of Range into Integer` when attempting to use an integer as the label for a graph. I found this error difficult to pinpoint for quite a while and was wondering if it  might be worth casting `label_text` as a String [here](https://github.com/topfunky/gruff/blob/master/lib/gruff/base.rb#L839). While I can now see why the error occurs, it was not obvious at the time and it seems to make sense to simply ensure that whatever has been passed as a label can in fact be stringified.

**Comment by donv** [comment]
Hi @jbcden !

Thanks for the report!  Can you make a pull request with the change you envision?  I'll merge it for you, especially if it contains a test :smile:

**Comment by Watson1978** [comment]
Seems thisissuealreadywasfixed.
