### ISSUE TITLE
setting a minimum_value creates an error in larger_than_max?

### ISSUE THREAD

**Issue by leonc** [topfunky/gruff#141]
If I set a minimum value and not a maximum, an error is generated from the larger_than_max? function:

Library/Ruby/Gems/2.0.0/gems/gruff-0.6.0/lib/gruff/base.rb:988:in `>': comparison of Float with nil failed (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.6.0/lib/gruff/base.rb:988:in`larger_than_max?'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.6.0/lib/gruff/base.rb:423:in `block in data'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.6.0/lib/gruff/base.rb:413:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/gruff-0.6.0/lib/gruff/base.rb:413:in `data'
    from ./generate-lf.rb:45:in`<main>'

The function in question is:
986     # Overridden by subclasses such as stacked bar.
987     def larger_than_max?(data_point) # :nodoc:
988       data_point > @maximum_value
998     end

**Comment by leonc** [comment]
Made a pull request for this. Not sure why the line graphs in test didn't uncover this. Makes me think I did something wrong to cause this, but I guess I'll wait on feedback from the PR.

**Comment by Watson1978** [comment]
This issue should be resolved by https://github.com/topfunky/gruff/pull/257
