### ISSUE TITLE
Be able to make graph wider than 800 pixels

### ISSUE THREAD

**Issue by slightlymadscience** [topfunky/gruff#144]
I have some graphs that have many labels that go into the legend.  Even when making the label (and the box) smaller, it still takes up a lot of space.  Most of the feedback even outside of this case were that they would like to have larger graphs.  Scaling up the image tends to be fuzzy, so 1200-1600 would be awesome.
Apologies if this has been posted before - hadn't seen it.

ps: I recently started using it, but have been leveraging it a LOT.  Great stuff.

**Comment by donv** [comment]
Hi @slightlymadscience !

This looks like something we could do.  Want to take a stab at it?

**Comment by Watson1978** [comment]
You can specify any image size for graph at the initializing.

```ruby
require 'gruff'

graph = Gruff::Bar.new('1600x1200') 
graph.data :hora, [6, 0, 0, 0, 0, 2, 8]
graph.write('test.png')
```
