### ISSUE TITLE
Is it possible to set font size only for axis (y or x) labels?

### ISSUE THREAD

**Issue by felipevieira** [topfunky/gruff#160]
In my example I have too many x axis values (values from 1 to 30) and I'm facing some overlapping issues that could be avoided if I could simply set the x axis labels font size to a smaller value. Any ideas?

![exciting](https://cloud.githubusercontent.com/assets/228709/18262814/62bd79fc-73db-11e6-8c14-c012c83ae57a.png)

**Comment by donv** [comment]
@felipevieira did you find a solution?

**Comment by felipevieira** [comment]
yes, @donv. I've figured out that I can set a wide range of font sizes using

`g = Gruff::Line.new('1500x700')
g.marker_font_size = 10
g.legend_font_size = 10
g.title_font_size = 20`

thank you

**Comment by rupurt** [comment]
@felipevieira can you post some examples? I can only seem to change  `legend_font_size` & `title_font_size`

**Comment by felipevieira** [comment]
@rupurt IIRC what you want can be achieved by setting marker_font_size

**Comment by felipevieira** [comment]
@rupurt iirc what you want can be achieved by setting `marker_font_size`

**Comment by rupurt** [comment]
@felipevieira cool. That worked. Do you have any ideas on how to center the x labels inside of a bar rather than center it around the starting data point?
