### ISSUE TITLE
Default scatter plot axes are not proportional to each other

### ISSUE THREAD

**Issue by tunamonster** [topfunky/gruff#165]
![circ-worst-120](https://cloud.githubusercontent.com/assets/11851707/20437284/ced90134-ade1-11e6-9e27-1157574b39e5.png)

In the image above I generated the points along the circles using the following code

```
random = Math::PI*2*rand
x_coord = Math.cos(random)
y_coord = Math.sin(random)

```
The outer circle has a constant multiple, but is otherwise the same as the inner unit circle.

Gruff seems to render circles as horizontally stretched ellipses.

In this case, it noticeably distorts the visual representation of the data, because we know what it is supposed to look like. 

For other point distributions it might result in skewed visuals, and lead to false visual impressions.

**Comment by Watson1978** [comment]
It would be useful to be able to easily draw on the square grid, but I have no plans to change the default behavior.
