### ISSUE TITLE
Prevent y axis values from being cast to float

### ISSUE THREAD

**Issue by c0ze** [topfunky/gruff#179]
I have some time interval data as integer values [1000, 1001, 1005] etc.

I noticed when I make a graph, the y axis are labels are converted to float (especially when the difference between min and max is less than the rows figured from the data). For example, if the max is 1001 and min is 1000, it splits the graph into 4 rows, and assigns float labels (1000.0, 1000.25, 1000.5, etc) which is annoying.

Is it possible to prevent this floating behavior ? And just make it set an arbitrary max ? (if min and max is 1000, and 1001 just make labels till 1004 etc.)

I notice the same behavior is also breaking my float data. I need to create float labels in `.2f` format, but they are being converted to `.3f` which is not very cool. It would be great if there was a way to set this behavior, and set a formatting formation for labels.

**Comment by noraj** [comment]
I have the opposite problem where my float values are rounded to integer.

Eg.

```
g3.data :Yes, 10.4 # => 10
g3.data :No, 89.6 # => 90
```

**Comment by noraj** [comment]
If we look for [label_formatting](https://github.com/topfunky/gruff/search?q=label_formatting&unscoped_q=label_formatting), we can see it is only set for side_stacked_bar, bar, side_bar and that `@label_formatting = nil` is set in base. So no other chart types can make use of it.

**Comment by AFlowOfCode** [comment]
I'm using a side bar graph and charting data that will only ever have an integer value, and by default they all show up as floats. Setting `g.label_formatting = "%d"` luckily fixes that.

I'm also not charting anything with a value of zero, so it never chooses 0 as a minimum on its own. Interestingly, this seemed to always force a float for the x-axis. At least in my case where there almost always is a bar with a value of 1, where 1 would then be set as the minimum (a bit unintuitively to me). `g.minimum_value = 0` turned all of x-axis labels into integers.

**Comment by AFlowOfCode** [comment]
It would be really great to have a way to specify that only integers should be used for markers. 

I haven't looked into how the calculation is happening under the hood, but sometimes they're floats, other times not. Finding it hard to predict & come up with some sort of algorithmic determination of min / max value combined with marker count to avoid that happening.

**Comment by AFlowOfCode** [comment]
I paid a little more attention to what was going on and figured it out. `vals` should be an array of all the numbers you're feeding gruff (as I mentioned above I'm excluding any 0 values).

```
# fix axis markers showing up as floats
if !vals.blank? && vals.max <= 4
  g.maximum_value = vals.max
  # marker count doesn't include the first marker, minimum_value
  # but it does include the last / maximum val
  g.marker_count = vals.max == 1 ? 1 : vals.max
elsif vals.max % 3 != 0 && vals.max % 4 != 0
  n = vals.max + 1
  g.maximum_value = (n % 3 == 0 || n % 4 == 0) ? n : n + 1
end
```
Without the above or any modification to the marker count or maximum value, below are the kinds of inconsistent default axis markers I'm getting. The "average" bar is the maximum value of the set. I screencapped 2 even maxes & 2 prime maxes to illustrate the problem with the way it is currently handled internally.

![gruff graph even 01 (float)](https://user-images.githubusercontent.com/14116237/112574686-70bd0e80-8db4-11eb-8697-b764431937e2.png)
![gruff graph even 02 (no float)](https://user-images.githubusercontent.com/14116237/112574691-71ee3b80-8db4-11eb-9240-c713d59f3cde.png)
![gruff graph prime 01 (float)](https://user-images.githubusercontent.com/14116237/112574694-71ee3b80-8db4-11eb-85ec-78991fb32b9b.png)
![gruff graph prime 02 (no float)](https://user-images.githubusercontent.com/14116237/112574696-731f6880-8db4-11eb-8556-7fd97c94c809.png)

I could look into making a PR for this if necessary.

**Comment by Watson1978** [comment]
I believe that the following two fixes solve this problem.

- https://github.com/topfunky/gruff/commit/37551dd14c05eebc4a58fa01a858e19f2d0feb85
  - The x and y coordinate values will no longer display unnecessarily long decimal points due to rounding errors.

- https://github.com/topfunky/gruff/pull/510
  - The x and y coordinate values can be formatted freely.

So, I will close this issue. but, feel free to reopen it as needed :)
