### ISSUE TITLE
 Error installing gruff windows 10

### ISSUE THREAD

**Issue by kustom001** [topfunky/gruff#184]
![ruby01](https://user-images.githubusercontent.com/47639287/52802253-de4bcc00-307f-11e9-8eec-8b06916a5803.PNG)

**Comment by Watson1978** [comment]
I think you installed ImageMagick 7.
Unfortunately, RMagick 2.16.0 does not support it.

The latest RMagick works with ImageMagick 7.
You can install gruff 0.8.0 that removed RMagick version dependency.
