### ISSUE TITLE
rmagic depenency has to update , gem installation  bug

### ISSUE THREAD

**Issue by rsurendraidexcel** [topfunky/gruff#189]
gem installation problem.. can you help
![gem_install_problem](https://user-images.githubusercontent.com/7713535/68529828-b6487b00-0328-11ea-8c57-2ac1782b2272.png)

**Comment by schmijos** [comment]
You need *imagemagick* 6. On MacOSX things would look like this to install

    PKG_CONFIG_PATH=/usr/local/Cellar/imagemagick@6/6.9.10-66/lib/pkgconfig gem install rmagick -v '2.16.0'

**Comment by Watson1978** [comment]
Released 0.8.0 that removed RMagick version dependency.
