### ISSUE TITLE
Release version 0.8.0

### ISSUE THREAD

**Issue by donv** [topfunky/gruff#191]
The main change is the version change of the rmagick dependency.

Any thoughts?

@topfunky

**Comment by Watson1978** [comment]
I want to remove the upper limit from `required_ruby_version` of gruff gem too (#207).
(Because Ruby 3.0 is scheduled to be released this year.)

**Comment by Watson1978** [comment]
Released v0.8.0
https://rubygems.org/gems/gruff/versions/0.8.0

**Comment by donv** [comment]
Nice!  Good work!
