### ISSUE TITLE
Empty data line graph throws undefined method exception

### ISSUE THREAD

**Issue by andrewngo** [topfunky/gruff#442]
### Description
Previously in v0.7, if you create an empty line graph, it will save a "No Data" image. In v0.10, it throws an undefined method exception.  

### Steps to Reproduce
```
g = Gruff::Line.new
g.data :"Test", []
g.write('some_path/some_file.png')

# NoMethodError Exception: undefined method `<=' for nil:NilClass
```
```
gruff (0.10.0) lib/gruff/base.rb:472:in `<='
gruff (0.10.0) lib/gruff/base.rb:472:in `data_given?'
gruff (0.10.0) lib/gruff/base.rb:428:in `draw'
gruff (0.10.0) lib/gruff/line.rb:167:in `draw'
gruff (0.10.0) lib/gruff/base.rb:411:in `write'
```
![image](https://user-images.githubusercontent.com/9726283/91627546-fd156900-e96c-11ea-8dd0-d0c1fe1db9f1.png)

### System Configuration
- ImageMagick version: ImageMagick 6.9.10-23 Q16 x86_64 20190101
- RMagick version: 2.16.0
- Gruff version: 0.10.0
- Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- Environment (Operating system, version and so on): Mac 10.14.6
- Additional information:

**Comment by Watson1978** [comment]
Thank you for reporting!
