### ISSUE TITLE
Single-Bar bar graph?

### ISSUE THREAD

**Issue by sdubinsky** [topfunky/gruff#605]
Hi,
Thanks for the library!  It's really great.  I'm on gruff 0.18.0, ruby 2.7.3, and ubuntu 22.04.  Perhaps I'm missing something obvious, but I can't figure out how to get a simple bar graph, where each line represents a single data point, and its length represents how far it goes.

I can fake this reasonably well with:
```
g = Gruff::Bar.new
g.hide_legend = true
data = {'A' => 1, 'B' => 2, 'C' => 3}
labels = {}

data.each_with_index do |arr, i|
  values = [0] * 10
  values[i] = arr[1]

  labels[i] = arr[0]
  g.data(arr[0], values)
end
g.labels = labels
g.write("graph1.png")

```

But that seems needlessly complex.  Is there a better/simpler way?

Also, the staggered labels option seems broken, even looking at the expected pic: https://github.com/topfunky/gruff/blob/master/test/expected/bar_set_label_stagger_height.png.

Thanks!

**Comment by Watson1978** [comment]
Maybe, you want to do is code something like the following?

```ruby
g = Gruff::Bar.new
g.hide_legend = true
data = {'A' => 1, 'B' => 2, 'C' => 3}

data.each do |key, value|
  g.data(key, [value])
end

g.minimum_value = 0
g.labels = data.keys
g.write("graph1.png")
```

I found that the labels are in the wrong place with my code, so I'm going to fix that.

> Also, the staggered labels option seems broken

It is expected. because staggered labels was deprecated.

**Comment by Watson1978** [comment]
If you have any other questions, please feel free to reopen this ticket.
