### ISSUE TITLE
Add support for spacing between groups of bar graphs

### ISSUE THREAD

**Issue by rosenfeld** [topfunky/gruff#7]
From what I've read, it is possible to add space between bars. And how about group of bars?

I mean, is it possible to define some spacing between bars and another spacing between groups of bars? If not, here is my feature request :)

Congratulations for Gruff!

**Comment by donv** [comment]
If you have the time, please make a pull request, and I will merge it.

**Comment by rosenfeld** [comment]
Thanks, @donv I'm using JavaScript client-side libraries for generating charts for several years now, and with two babies at home it's hard to find time to work on side projects :) Feel free to close this ticket if you prefer :)

**Comment by Watson1978** [comment]
this issue should be resolved with  #400
