### ISSUE TITLE
Beizer: too wide left margin with some floating points

### ISSUE THREAD

**Issue by mdesantis** [topfunky/gruff#87]
With this code

``` ruby
require 'gruff'

g = Gruff::Bezier.new
g.data 'test', [0.00233034904691358, 0.0024406001456790108,
                0.008512412911111114, 0.03504837642469136, 
                0.3403206903185184, 2.9516386719456804]

g.write('gruff_test.png')
```

the resulting graph has a too wide left margin:

![gruff_test](https://f.cloud.github.com/assets/283320/1191672/ddde45f4-2455-11e3-81a0-d5ca849d44bd.png)

A quick fix is to set manually a "short" (from the text width point of view) maximum value:

``` ruby
require 'gruff'

g = Gruff::Bezier.new
g.data 'test', [0.00233034904691358, 0.0024406001456790108,
                0.008512412911111114, 0.03504837642469136, 
                0.3403206903185184, 2.9516386719456804]
g.maximum_value = 2.96
g.write('gruff_test.png')
```

![gruff_test](https://f.cloud.github.com/assets/283320/1191716/7b4fc72c-2456-11e3-8b73-a635359ed000.png)

**Comment by Watson1978** [comment]
It reproduces the same data even if it generates other graphs.

https://github.com/topfunky/gruff/blob/3e54c0d5ef45c182dcb891ede3d54fa99f3e7dd9/lib/gruff/base.rb#L551-L552

It looks like the problem is that `@increment` is `nil` when determining the width of the label
