### ISSUE TITLE
Pie chart colors do not show up

### ISSUE THREAD

**Issue by jonathanamccann** [topfunky/gruff#96]
require 'Gruff'

pie_chart = Gruff::Pie.new
pie_chart.data 'Solved', 10
pie_chart.data 'Action Required', 60
pie_chart.data 'Disconnected', 10
pie_chart.data 'Call Back', 10
pie_chart.data 'Transfer', 10
pie_chart.theme = Gruff::Themes::PASTEL
pie_chart.write("association_disposition_pie_chart.jpg")

The above code produces an all black/white chart, although the theme is clearly set to PASTEL. The data labels pick up the pastel colors, but the actual chart colors are black and white. A screenshot can be found here:

http://i39.tinypic.com/33ne1r6.jpg

**Comment by Watson1978** [comment]
I tried to reproduce this issue with latest RMagick.
However, I can't. So, I will close this.

Feel free to re-open if you needed.
